Remove the pagination-aware processing of search request results
spine-examples/Pingh pull request #39
Opened 2024-09-24 10:07 UTC by MykytaPimonovTD

When performing a GitHub REST API search request, pagination was previously used, with up to 100 items per page and additional requests made if not all items were returned to the initial response.

However, pagination is unnecessary for this case, as the data volume is small. This changeset removes pagination-aware processing of search results.

Now, the number of requested items is capped at 20, without additional requests. On the first launch, the user will see up to 20 mentions from the last workday.

2024-09-24 11:04 UTC, armiol commented
@MykytaPimonovTD is it correct, that we load 20 items just for the first time user opens the application (that's what we discussed previously)? Or do we always load just 20 items? Please clarify.

Another thing is that this isn't quite true:

> ... the user will see up to 20 mentions from the last workday.

Users will see 20 of the most recent mentions. I don't understand where did you take "the last workday" from. Or is it my understanding that's incorrect?

2024-09-24 11:47 UTC, MykytaPimonovTD commented
> @MykytaPimonovTD is it correct, that we load 20 items just for the first time user opens the application (that's what we discussed previously)? Or do we always load just 20 items? Please clarify.
> 
> Another thing is that this isn't quite true:
> 
> > ... the user will see up to 20 mentions from the last workday.
> 
> Users will see 20 of the most recent mentions. I don't understand where did you take "the last workday" from. Or is it my understanding that's incorrect?

@armiol The PR description has been updated based on the comments.

2024-09-24 17:15 UTC, armiol requested changes
@MykytaPimonovTD please see my comment.

2024-09-24 17:15 UTC, armiol commented on mentions/src/main/kotlin/io/spine/examples/pingh/mentions/RemoteGitHubSearch.kt
> +        onlyOnFirstPage: Boolean
Instead, you should have an optional parameter `limit` (an integer number), which would mean "return no more than $limit of most recent mentions" if set.

The name is chosen to sound familiar to those who previously have used SQL.

2024-09-25 10:59 UTC, armiol approved these changes

2024-09-25 11:00 UTC, merged