Enable Google Cloud Scheduler
spine-examples/Pingh pull request #43
Opened 2024-10-03 14:12 UTC by MykytaPimonovTD

The Pingh server has processes that change state after a specific period, such as updating mentions from GitHub, refreshing the access token, and changing mention state from snoozed to unread.

This changeset configures an additional server to handle requests sent by Google Cloud [Scheduler](https://cloud.google.com/scheduler/docs/overview) at regular intervals and emit `TimePassed` events with the current timestamp.

The Scheduler task sends an HTTP request with an empty body to the Pingh server and is [configured](https://cloud.google.com/scheduler/docs/configuring/cron-job-schedules) to run every minute using the following unix-cron format expression: `* * * * *`.

The server handling Scheduler requests starts alongside the Pingh server and listens on port `8080`, so ensure this port is open.

2024-10-03 14:26 UTC, armiol commented
@MykytaPimonovTD In debugging purposes, I suggest we first run it every two or three minutes. Otherwise, it will be difficult to follow the potential issues by observing logs. The thing is there is going to be too much output produced too often.

2024-10-03 14:29 UTC, armiol commented
@MykytaPimonovTD Another thing is that it would be good to allow the connections only initiated by the Cloud Scheduler. And reject all the requests coming from anywhere else.

Please investigate the options in the scope of the upcoming PRs.

2024-10-03 14:35 UTC, MykytaPimonovTD commented
> In debugging purposes, I suggest we first run it every two or three minutes. Otherwise, it will be difficult to follow the potential issues by observing logs. The thing is there is going to be too much output produced too often.

@armiol Done. Currently, the Google Cloud Scheduler sends requests every three minutes.

2024-10-03 15:53 UTC, armiol requested changes
@MykytaPimonovTD as discussed vocally, let's reorganize the way of communication between third-party and domain contexts, so that they are explicitly created over the same server environment settings (including the transport factory).

Another thing is that there's a lot of different "client"-related variables in scope of `PinghServer`, but they speak of different clients.

Please address the comments, and let me know.

2024-10-04 12:53 UTC, armiol requested changes
@MykytaPimonovTD see my comments.

2024-10-04 12:53 UTC, armiol commented on server/src/main/kotlin/io/spine/examples/pingh/server/UpdateCheckServer.kt
> +            clock.triggerTimePassed()
All we do here is listen for time intervals. I would say it's called "heartbeat".

Therefore, this isn't an update check server. And the endpoint isn't `/check-for-updates`.

2024-10-04 12:53 UTC, armiol commented on sessions/src/main/kotlin/io/spine/examples/pingh/sessions/RemoteGitHubAuthentication.kt
> +                .with(gitHubApp.id)
Here and below: why don't we pass the `GitHubApp` instance itself?

2024-10-04 12:53 UTC, armiol commented on server/src/main/kotlin/io/spine/examples/pingh/server/PinghApplication.kt
> + * without starting it. Additionally, provides a service that enables the emitting events
> Additionally, provides a service that enables the emitting events
> with the current time to the Pingh server.

"events with the current time" does not make too much sense.

```
The server side of the Pingh application.

During the initialization, performs the actions as follows.

1. Configures the server environment for production use,
including the interaction with GitHub API, Google Datastore, etc.

2. Starts an [HTTP endpoint](we need the link to our implementation here)
receiving the current time values from an external clock or a system scheduler.
```

2024-10-04 15:10 UTC, armiol approved these changes
@MykytaPimonovTD please address my comment. In general, LGTM.

2024-10-04 15:10 UTC, armiol commented on clock/src/main/kotlin/io/spine/examples/pingh/clock/ClockContext.kt
> + * Use only for test.
There are a lot of better options:

*  "in testing purposes", 
* "for testing",
* "in tests".

JFYI.

2024-10-04 15:28 UTC, merged